pnpm/pnpm.io

docs/continuous-integration.md
Hi, just thought I would add instructions on how to use pnpm on [Sail CI](https://sail.ci/).
Also, have you thought about maintaining an official Docker image for pnpm that you automatically update with each release? I found [znck/docker-pnpm](https://hub.docker.com/r/znck/docker-pnpm/) which was quite comprehensive but it stopped getting updated about 5 months ago.
=> Add Sail CI info to Continuous Integration page

docs/configuring.md, docs/faq.md
Closes pnpm/pnpm#1515
Added docs to clarify how pnpm usage on multi-filesystem computers.
This information was deduced based on pnpm/pnpm#712, related issues and PRs, and the current code located [here](https://github.com/pnpm/pnpm/blob/36b53268f09796a6393f00ca38a0c4b68d3055c2/packages/package-store/src/storeController/createImportPackage.ts#L56)
=> Documentation on multi-filesystem support

docs/pnpm-install.md
1. Add documentation for `--ignore-scripts`
similar to [yarn](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-ignore-scripts)
2. Add documentation for `--production`
similar to [yarn](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-production-true-false)
=> Add documentation for `--ignore-scripts` and `--production` flags

docs/pnpm-cli.md
The links don't work when they have the .md ending - removing the .md fixes the links.
=> Fix links in documentation

docs/only-allow-pnpm.md
The shortening is just for cuteness, but providing the user with the `npx` command makes it always work.
Furthermore, the backticks were being evaluated, using single quotes makes bash ignore them. Now the command works.
=> only-allow-pnpm: fix and use npx

docs/only-allow-pnpm.md
It looks like the "`" back tick makes yarn and pnpm hang.
Removing them make yarn console the message and pnpm works like expected!
=> Fix only-allow-pnpm example

website/i18n/en.json, website/versioned_docs/version-4.9/completion.md
Small typo in the docs, **Command line tab-comletion** should be **Command line tab-completion**
=> fix typo: replace 'comletion' with 'completion'

docs/cli/update.md
Changes "dopependencies" to "dependencies" in [`docs/cli/update.md`](https://github.com/pnpm/pnpm.github.io/blob/976cc8aa144bd208d8eb54e9dbf9f141bd0847e3/docs/cli/update.md). That's it.
It was a pretty dope typo though, haven't seen many like it. :)
=> Fix typo in update.md

docs/about-the-package-store.md
I believe after inspecting both the file generated, and the source here: https://github.com/pnpm/pnpm/blob/v4.14.3/packages/types/src/store.ts
It seems the store json is actually the inverse of what's documented
=> Package store documentation out of sync

docs/cli/store.md, website/versioned_docs/version-3.8/cli/store.md, website/versioned_docs/version-4.0/cli/store.md, website/versioned_docs/version-5.0/cli/store.md
Docusaurus uses `id` in metadata to link docs, not file name.
> New markdown files within docs will show up as pages on the website. Links to those documents are created first by using the id in the header of each document. If there is no id field, then the name of the file will serve as the link name.
>
> https://docusaurus.io/docs/en/navigation#how-documents-are-linked
And `about-the-package-store.md` has an `id` not matching its file name:
https://github.com/pnpm/pnpm.github.io/blob/source/docs/about-the-package-store.md#L2
Looks like this link was broken since it exists.
=> Fix broken link to about package store

docs/using-changesets.md
I'm not 100% sure my new text is correct, but I am sure the old text was not correct. `pnpm changeset version` doesn't bump **all** package versions. I had been scared to run it because I thought that's what it would do, but when I actually ran it then it only bumped versions for a couple of packages.
=> Fix description of which package versions are bumped

src/pages/index.js
Adds a better meta description for shared links 
Old:
=> Set tagline as meta description for frontpage

benchmarks/commandsMap.js
Setting these should more accurately compare performance as `yarn` & `pnpm` do not audit or install peer-deps by default.
=> Set --no-audit & --legacy-peer-deps in benchmarks for npm

docusaurus.config.js
Currently the edit link points to a `source` branch which does not exist, resulting in anyone pressing the "edit this page" button hitting GitHub's 404.
This pr just changes the branch to `main` so you can edit the page
=> Updates edit link to point to main branch

docs/cli/add.md, versioned_docs/version-4.x/cli/exec.md, versioned_docs/version-5.x/cli/add.md, versioned_docs/version-5.x/cli/exec.md, versioned_docs/version-6.x/cli/add.md, versioned_docs_archived/version-2.x/cli/add.md, versioned_docs_archived/version-2.x/cli/exec.md, versioned_docs_archived/version-3.x/cli/exec.md
Related string/issue on Crowdin: https://crowdin.com/translate/pnpm/2976/en-ru#97282
=> fix typo inside `add.md`: `Exempli gratia` -> `For example`

docs/cli/prune.md
I wasted some time wondering why prune didn't work as expected, and it made sense once I discovered the command isn't monorepo-aware. I thought perhaps others would enjoy some notice on that. WDYT?
=> Warn that prune is not monorepo-aware at this time

docs/continuous-integration.md
The latest `actions/setup-node@v2` supports caching `pnpm` packages dependencies out-of-the-box with a requirement of `pnpm` **v6.10+**.
Closes #154
=> docs: update GitHub Actions guide

users.json
This is a quick fix for #181 where I've resized the @pabio logo to be visually similar to the ones next to it.
Before:
After:
=> fix: Visually similar logo height for `/users`

docs/cli/import.md
As running **pnpm import** without having declared workspaces just imports the dependencies of the root package.json
=> pnpm import - mention workspaces having to be set

docs/npmrc.md
The default value of `enable-modules-dir` is `true`, but it's currently documented as `false`.
https://github.com/pnpm/pnpm/blob/v6.29.1/packages/config/src/index.ts#L179
https://github.com/pnpm/pnpm/pull/3051/files#diff-2eafc75a9015704b121dff9585728616f562e1625da9a53e44a86cacb94ae619R150
=> fix(npmrc): `enable-modules-dir` default is `true`

docs/uninstall.md, versioned_docs/version-6.x/uninstall.md
If pnpm is installed using the `https://get.pnpm.io/install.sh` standalone script (in the "Node.js is not preinstalled" subsection), these two lines are added to the shell configuration file:
```
export PNPM_HOME="/home/username/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
```
=> update uninstall.md (add reference to the PNPM_HOME)

src/pages/index.js, src/pages/users.js
Provide users of pnpm with more accurate analysis data. Let them know how many `PV/UV` are obtained through pnpm.
=> refactor: add utm params in url

docs/continuous-integration.md
Updates gitlab example to cache based on lock files content for far more robust and reused caches.
=> Update gitlab example

blog/2020-05-27-flat-node-modules-is-not-the-only-way.md
`.modules.yaml` file is located in `node_modules` folder not in `exrpress`.
=> docs: correct nesting level for .modules.yaml

docs/pnpm-workspace_yaml.md
As well-illustrated here, the documentation of `packages/**` will result in checking at arbitrary depths for `package.json` files in a misguided attempt to find workspaces. This isn't the way most humans would construct project layouts and is a performance footgun: https://github.com/vercel/turborepo/issues/667#issuecomment-1128057910
=> Avoid looking for packages at infinite depth.

docs/package_json.md
`patchedDependencies` was missing under `pnpm`.
=> Fix example of patchedDependencies docs

docs/cli/install.md
I noticed --ignore-scripts was missing from the documentation, so I added it here.
=> Added --ignore-scripts argument to documentation

docs/completion.md
[Fig](https://fig.io) provides autocomplete for 300+ CLI tools including pnpm. It looks like this:
We think this will help users become more efficient with pnpm CLI, so we would love to have Fig listed as an autocomplete method in your docs. Thanks so much and please let me know if you have any questions!
=> Add Fig as an autocomplete method

src/css/customTheme.css
Carbonads text is not seeing properly when we enable the dark mode. I fixed some css styles to properly visible in both light+dark modes.
=> Carbonads text fixed when dark mode enables

docs/continuous-integration.md, docs/using-changesets.md, versioned_docs/version-6.x/continuous-integration.md, versioned_docs/version-6.x/using-changesets.md
[actions/checkout](https://github.com/actions/checkout) is on `v3`.
[actions/setup-node](https://github.com/actions/setup-node) is on `v3`.
=> docs github actions versions

community/tools.md
Aspect's rules_js replaces Bazel's built-in JS support by leveraging pnpm.
Read https://blog.aspect.dev/rules-js in case you're curious.
=> Add Bazel to the list of pnpm-supporting tools

docs/continuous-integration.md
- Fixes https://github.com/pnpm/pnpm/issues/4412 .
- Add Jenkins examples to Continuous Integration.
=> Add Jenkins examples to Continuous Integration

docs/installation.md
`wget` is included in vanilla alpine (`docker run alpine`)
=> docs: alpine wget instead of curl

docs/cli/fetch.md
Small tweaks to `docs/cli/fetch.md` to tidy up the wording and reduce ambiguity.  Thanks for the great work on pnpm!
=> Grammatical fixes for docs/cli/fetch.md

docusaurus.config.js
Fixed incorrect display of the year in сopyright in the footer. Now the year is automatically calculated
=> fixing the year in the footer

src/pages/benchmarks.md
https://pnpm.io/benchmarks
> says daily, was days ago
https://github.com/pnpm/pnpm.github.io/commit/3c03b982d1b44d5df37a4c6cda14e6675d4f896f indicates the benchmark interval changed from daily to [weekly](https://github.com/pnpm/pnpm.github.io/actions/workflows/benchmark.yml)
> not sure about that end of file diff with the image, I didn't touch that part and edited through their GUI. perhaps it's an artifact of the github action not giving it a EOF character?
=> fix(benchmarks): update benchmark interval label

docs/cli/install.md
removed unnecessary single quote escape, in the docs this is rendered with `\`
https://pnpm.io/cli/install#--force
=> docs(cli): remove unnecessary escape

docs/npmrc.md
Priority usage of `process.env.PNPM_HOME` for the store-dir was added Oct 29, 2022 in https://github.com/pnpm/pnpm/pull/5566.
This documentation change reflects that addition and how it's usage is slightly different from `process.env.XDG_DATA_HOME`.
=> add usage of PNPM_HOME env variable for store-dir

docs/cli/list.md
I was confused why `pnpm list` was not returning results, until I found https://github.com/pnpm/pnpm/issues/1932, explaining the default for `--depth` and how to get all depths.  This adds that information to the docs to help others.
=> Explain "list" depth default and how to list all

docs/package_json.md
The `"overrides"` field should be in the `"pnpm"` field.
=> Fix pnpm.overrides examples

docs/installation.md
Starting today, pnpm is available on Chocolatey as well.
Like Scoop, Chocolatey is a package manager for Windows. Personally I only use Choco and not Scoop.
Choco pnpm installation page: https://community.chocolatey.org/packages/pnpm
Source of the choco package (installation script): https://github.com/MKMZ/ChocolateyPackages/tree/main/pnpm
- Add choco as a documented way to install pnpm.
=> docs(installation): add choco method

docs/npmrc.md
Without this fix, the doc says the `hoist` config will hoist deps to `node_modules/.pnpm`, which is the location of virtual store. It create confusion between "hoisted packages" and  "packages in virtual store". Only when I see [this answer](https://github.com/orgs/pnpm/discussions/4224#discussioncomment-1955163) I realized pnpm created `node_modules/.pnpm/node_modules`!
=> Clarify `hoist` location

docs/cli/patch-remove.md, sidebars.json, versioned_sidebars/version-8.x-sidebars.json
show "Patch Depedenencies" category in  "CLI Commands":
=> fix: show patch dependencies category

docs/continuous-integration.md
Currently the online CI example cannot work, it has two errors,
1. The Node.js must >= 16.14
2. Corepack can not use  `@latest-8 syntax`
So I updated docs, at least it can work, it will friendly for developers
=> docs: Update gitlab and bitbucket CI docs, friendly for developers

docs/cli/config.md
fix spelling of `set` and add config options
=> docs: fix spelling of set and add config options

docs/docker.md
I made a mistake by only mention the store directory. But in order to actually utilize reflinks, `node_modules` have to be mounted too.
=> docs: mention node_modules

docs/docker.md, docs/podman.md, sidebars.json, versioned_sidebars/version-8.x-sidebars.json
I mistakenly assumed that all options in docker is the same as podman, turns out it wasn't the case
=> docs: replace `docker` with `podman`

docs/cli/install.md, docs/git_branch_lockfiles.md, docs/npmrc.md, sidebars.json, versioned_docs/version-7.x/cli/install.md, versioned_docs/version-7.x/git_branch_lockfiles.md, versioned_docs/version-7.x/npmrc.md, versioned_sidebars/version-7.x-sidebars.json, versioned_sidebars/version-8.x-sidebars.json
Add documents for git branch lockfiles feature.
=> :memo: git branch lockfiles

docs/cli/run.md
See https://github.com/pnpm/pnpm/issues/7061
On a sidenote: the option `--reporter=<name>` is only documented on the [install command](http://localhost:3000/cli/install#--reportername), even though it's also valid for the [run command](http://localhost:3000/cli/run#--aggregate-output) and mentioned in there. If you want, I could copy the reporter block over to run.
Let me know what you think.
=> add --reporter-hide-prefix

docs/package_json.md
Docs change for pnpm/pnpm#7174.
=> docs: document `resolutions` and `pnpm.overrides` merging

docs/cli/exec.md, versioned_docs/version-7.x/cli/exec.md, versioned_docs_archived/version-2.x/cli/recursive.md, versioned_docs_archived/version-2.x/pnpm-recursive.md, versioned_docs_archived/version-3.x/cli/recursive.md, versioned_docs_archived/version-3.x/pnpm-recursive.md, versioned_docs_archived/version-4.x/cli/recursive.md, versioned_docs_archived/version-4.x/pnpm-recursive.md, versioned_docs_archived/version-5.x/cli/recursive.md, versioned_docs_archived/version-6.x/cli/exec.md
Correct `$PNPM_PACKAGE_NAME` usage for `exec` cli documentation, because `$PNPM_PACKAGE_NAME` still empty when we execute `pnpm -rc exec pnpm view $PNPM_PACKAGE_NAME`, this command equivalent to `pnpm -rc exec pnpm view `.
So we should to escape it, to save the original token for execute the real command we expect.
Another question, why `pnpm -rc exec pnpm view $PNPM_PACKAGE_NAME` looks work? Because even if there are no cli argument, `pnpm view` can also works in package directory.
=> docs: correct pkg env usage for exec cli

docs/git_branch_lockfiles.md
The .npmrc config page includes the correct property name, which is singular, not plural.
=> Docs: Fix git-branch-lockfile property name

src/css/customTheme.css
The default font-family in tailwind is very Mac-centric and lacks consideration for Windows environments, especially CJK Windows environments.(Note: https://infinnie.github.io/blog/2017/systemui.html)
Currently, tailwind's font-family for sans serif is preceded by system-ui, which results in rendering Malgun Gothic instead of Segoe UI in Korean window environments. Malgun Gothic's readability in English is horrendously bad. This PR fixes that issue.
This is a screenshot of the at-proto site in a Korean Windows environment. You can see that the English is not very readable.
This is a screenshot taken after removing system-ui from the font-family. You can see that the Segoe ui is rendered and is more readable.
=> Improve font fmaily

docs/docker.md
/dev is a reserved path on linux for hardware mount points, the example as it stands currently will not work, as COPY . /dev does not actually copy files and the install command afterwards fails
=> Replace /dev path with /usr/src/app in docker example

versioned_docs/version-7.x/git_branch_lockfiles.md
Changes incorrect `git-branch-lockfiles` config option to `git-branch-lockfile` in v7 docs. The correct name is already used in the v8 docs.
=> Fix to documentation for `git-branch-lockfile`.

docs/package_json.md
The wording before this PR has costed me half a week trying to find a bug that doesn't exist.
=> docs(injected): more accurate description

users.json
Hi!
I'd like to propose my project, tinyhttp, to be added to a list of projects using pnpm.
It was added before in #77 but the configs were moved around tinyhttp got lost :(
Since the PR was merged, tinyhttp grew from 250 stars to 2500 stars and pnpm still works great for tinyhttp!
=> add tinyhttp to the list of users

docs/cli/publish.md
As the title suggests, the JSON example had a typo.
=> docs: fix json for pnpm-publish-summary.json example

docs/workspaces.md
Ember was previously added as user in this PR: https://github.com/pnpm/pnpm.io/pull/490
This PR adds the repo as a workspace example in the docs.
=> docs: add Ember as pnpm workspace project

docs/filtering.md
Due to the missing semicolon, this was rendering as `&ltglob>` instead of the intended `<glob>`
=> Fix placeholder in header

docs/workspaces.md
I added Material UI in the same sort DESC stars order. The PR in question: https://github.com/mui/material-ui/pull/36287.
The page: https://pnpm.io/workspaces#usage-examples.
Hopefully, this will further help convince developers that pnpm is now a better choice than yarn. I mean, I think that developers who are considering pnpm should see this list, this looks like a very powerful marketing tool to me, maybe to make it easier to discover from the homepage.
=> docs: add Material UI to the showcase

docs/cli/install.md
The `--prod` flag for the `pnpm install` command is not well displayed as a boolean value.
It is unclear that one can use the flag like this `pnpm install --prod=false` to use a "development" install in a production environment. This has already happened to some people: https://github.com/pnpm/pnpm/issues/6254 
This PR tries to explain the option a bit better, so its use-case is a bit more clear, and aims to make the docs page more consistent.
I took inspiration from how the `--frozen-lockfile` option works: https://pnpm.io/cli/install#--frozen-lockfile
=> docs: improve explanation of --prod flag

docs/continuous-integration.md
My understanding of how pnpm caching works means that the pnpm store should get cached, not `node_modules`.
This brings the CircleCI config inline with the other examples.
=> Fix CircleCI caching config

docs/installation.md
The current instructions were a bit outdated, so I'm suggesting a few updates:
- `corepack enable` currently also installs Yarn. It might make sense to restrict it to pnpm.
- Since https://github.com/nodejs/corepack/pull/134, the version folks get when installing Corepack should always be the latest.
- We could talk about package-pinning with `corepack use`.
=> Update Corepack instructions in `installation.md`

docs/cli/update.md
https://github.com/pnpm/pnpm/pull/7466
=> docs(cli): correct `--latest` to follow merged PR

docs/package_json.md
An example in docs was m.issing comma and I couldn't leave it like that.
Here is a [link to docs](https://pnpm.io/package_json#publishconfiglinkdirectory)
=> docs: add a missing comma to an example of publishConfig.linkDirectory

docs/how-peers-are-resolved.md
The page that the old link points to appears to have moved. The old link still leads to the correct page, due to redirecting on NPM's side, but the link to the #peerdependencies id no longer appears to work.
=> Updated link to npm's peer dependency documentation

docs/cli/exec.md
I just noticed that mistakenly I inserted `--no-reporter-hide-prefix` section into between the `--recursive, -r` section.
=> docs(exec): correct examples section

docs/cli/dlx.md
Other docs have aliases listed. E.g. https://pnpm.io/cli/update has `up` and `upgrade`
I wrote this one out in a bit longer format so that no one would think you should run `pnpm pnpx`
=> docs: list `pnpx` as alias for `pnpm dlx`

docs/catalogs.md, docs/pnpm-workspace_yaml.md, sidebars.json
Adding docs for:
- https://github.com/pnpm/rfcs/pull/1
- https://github.com/pnpm/pnpm/releases/tag/v9.5.0
- Is it worth writing a comparison to `pnpm.overrides`? This [was in the RFC](https://github.com/pnpm/rfcs/blob/main/text/0001-catalogs.md#comparison-to-overridesresolutions), but I don't think it'll be that common of a user-facing question.
- Anything I forgot to mention? 🙂
=> Add docs for catalogs

docs/catalogs.md
update the doc and include codemod for catalog.
=> doc: add codemod for catalog

docs/catalogs.md
`pnpm pack` also removes the `catalog` protocol. I had to debug this locally to be sure but the documentation should be updated to clearly explain this.
=> Update catalogs.md to include pnpm pack

docs/docker.md
On the docker documentation, most of the docker examples use BuildKit cache mounts, which are a great option locally or when building the image on only one machine, but when you're using a CI/CD pipeline, this kind of cache might not be available, and only normal docker cache will suffice (eg: Kaniko).
So I added an example for this scenario.
=> docs: improve working with cache doc

docs/cli/deploy.md
Closes https://github.com/pnpm/pnpm/issues//7286
The packlist generation used by pnpm deploy is significantly more complex than the docs currently suggest which resulted in a few lost hours for me figuring out why my `dist` directory was missing (it was .gitignored).
I believe the rules come from https://www.npmjs.com/package/npm-packlist or at least mimic the rules from that package but I couldn't follow the src in the time I had available to be honest.
Instead I made a test repo to check the behaviour described in this PR, it's over here if you want to check my work https://github.com/antiBaconMachine/pnpm-deploy-packlist-examples/tree/main.
If someone could confirm that deploy does indeed use npm-packlist then it might be better to just link straight to that more complete …
=> chore(deploy): Add some clarrification for deploy packlist generation

docs/npmrc.md
I had a rough time to figure out which page on the docs would tell me how to change the main directory on where packages get installed at and etc. until I figured out that the .npmrc page is the Main Configuration for the pnpm CLI.
=> Suggestion to re-title the .npmrc Configuration

docs/completion.md
This PR adds the command for generating pnpm autocompletions in the Fish shell to the completion documentation on [pnpm.io/completion](https://pnpm.io/completion), aligning it with the existing instructions for Bash.
```
pnpm completion fish > ~/.config/fish/completions/pnpm.fish
```
Local preview of the PR:
=> docs(completion): added completion command for fish shell

docs/catalogs.md
The `peerDependencies` field in the package.json file works with the `catalog:` protocol but is not documented yet.
My package.json and pnpm-workspace.yaml look like this for example:
When I inspect the package.json file inside the tarball created by `pnpm pack` it got replaced as expected:
=> docs: add `peerDependencies` as a supported `catalog:` protocol field

docs/errors.md
Extend the docs for the error `ERR_PNPM_MISSMATCHED_RELEASE_CHANNEL` to hint that node version definitions like `lts/Jod` are not allowed.
I am migrating from `nvmrc` and was used to this way of specifying the node version. This addition would have saved me a few minutes of additional research.
=> Docs: errors.md: Extend `ERR_PNPM_MISSMATCHED_RELEASE_CHANNEL`

docs/pnpm-workspace_yaml.md
While submitting [another issue](https://github.com/vercel/turborepo/issues/9490), I realized that it'd be nice to document how to specify a package directory without a wildcard. It's pretty basic/obvious, but I think it'd be nice to state it explicitly.
=> Add an example to `docs/pnpm-workspace_yaml.md` that doesn't use a wildcard

docs/installation.md
Corepack is now bundled within the Homebrew formulae for Node.js
=> chore: corepack is bundled with nodejs on brew

docs/workspaces.md
For some reason, the permalink to bit blog has changed. This tiny PR fixes the link.
=> fix(docs): fix broken link to bit.dev blog in workspaces page

docs/package_json.md
https://github.com/pnpm/pnpm/pull/8897 flipped the default value for `pnpm.onlyBuiltDependencies` so that no npm install scripts are run unless specifically allowlisted.
This PR clarifies the language in the documentation to reflect this new default.
=> docs: clarify v10 default value for `pnpm.onlyBuiltDependencies`

docs/uninstall.md
if `$PNPM_HOME` or `$(pnpm store path)` expand to values with a space character, then the shell will treat it as two different arguments for `rm` to delete.
Depending on where the space is, it could delete something bad.
But putting double quotes around it, we prevent that, and the shell will always treat is as a single argument
=> Put double quotes around rm command args

docs/cli/add.md
Any posix shell out there will fork a process if you pass `&` as a command line parameter without escaping it, see https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html.
I suggest we escape it in the docs too, so people can copy&paste the command directly.
=> doc(add): Escape ampersand in shell

docs/cli/install.md
https://pnpm.io/cli/install doesn't currently list this option.
References:
- [pnpm/pnpm/pkg-manager/plugin-commands-installation/src/install.ts#L122-L125](https://github.com/pnpm/pnpm/blob/002f6febe489ffefb004110ee5c83c8c2ff80fd2/pkg-manager/plugin-commands-installation/src/install.ts#L122-L125)
- [pnpm/pnpm/pnpm/test/install/misc.ts#L50-L58](https://github.com/pnpm/pnpm/blob/002f6febe489ffefb004110ee5c83c8c2ff80fd2/pnpm/test/install/misc.ts#L50-L58)
=> Document `pnpm install`'s `--no-lockfile` option

docs/cli/install.md
Resolves https://github.com/pnpm/pnpm/issues/9147
=> docs: notes for dependencies filtering

docs/settings.md
`auditConfig.ignoreCves` and `auditConfig.ignoreGhsas` fields expect arrays, so the lines should start with `- ` in YAML.
=> docs: fix auditConfig examples

docs/settings.md
This allows you to not have NODE_OPTIONS specified. The spaces seem to be removed internally by node js thankfully
=> Tweak node options syntax

docs/continuous-integration.md
Nitpicking, but it felt weird to have the list unordered, so I had to rely on the table of contents, but even there, it was confusing. I figured it would be beneficial to have this list sorted in alphabetical order.
=> docs: sort continuous integration recipes in alphabetical order

docs/cli/add.md
Today when trying the command from <https://pnpm.io/cli/add#install-from-a-subdirectory-of-a-git-repository>, I encountered a `Repository not found` error. Later I discovered that `RexSkz/test-git-subdir-fetch` has been renamed to `RexSkz/test-git-subfolder-fetch`.
This PR updates the documentation to reflect the current repository name.
=> docs: update URL of git subfolder test repository

docs/cli/config.md
Document the default of the `--location` flag for `pnpm config` commands
It appears that the default of the `--location` setting for `pnpm config` is `global`:
```bash
$ pnpm config set x true
$ pnpm config get x
true
$ cat "$HOME/Library/Preferences/pnpm/rc"
x=true
```
=> Document default of `--location` for `pnpm config`

docs/settings/_shellEmulator.mdx
Node.js 22+ supports `node --run` without pnpm, but it does not respect `shellEmulator`. It should be warned that `pnpm run` is required to run scripts that depend on Bash features.
=> docs: add note about Node.js 22+ script execution without pnpm

docs/installation.md
This adds a little tip on the installation page with a quick way to add pnpm store to the list of excluded folders in Microsoft Defender, which can **significantly** speedup installation speeds, from 5+ minutes to just a few seconds.
=> docs: add tip about excluding pnpm in Microsoft Defender
