pnpm/pnpm.io

docs/faq.md
=> Fix typo and grammar in FAQ

docs/hooks.md
This is just stuff I struggled with when writing the `pnpmfile.js` for Cycle.js.
The example is adapted from the example in the Medium post. The shrinkwarp.yaml also took me a while to figure out.
=> Clarify the hooks sections

docs/faq.md
- ADDED: easiest solution for missing deps
=> DOCS: How to quickly resolve missing deps

website/pages/en/index.js
Closes #23
- Fixed warnings that show up when running `pnpm start`
- Launched website and ensured all affected code still functions
- Manually inspected HTML to ensure properties are being set
=> Fix pnpm start warnings

docs/faq.md, docs/pnpm-store.md
Closes #25 
- Refactored documentation for `pnpm store <command>`
- Added documentation for `pnpm store usages`
- Cleaned up description of `pnpm store prune`
- Launched server
- Ensured docs and FAQ were correct
=> Add documentation for `pnpm store <command>`

docs/continuous-integration.md
Thanks to @qm3ster for [motivating me](https://dev.to/qm3ster/comment/8p06) to write this. :)
=> Semaphore 2.0 CI example configuration

website/siteConfig.js
Things we need:
* API KEY
* About the **indexName** not pretty sure
* https://docusaurus.io/docs/en/search#docsNav
=> docs: enable search

website/core/Footer.js, website/pages/en/Footer.js, website/pages/en/index.js, website/pages/en/index.js.txt
Fixes #47 
Ran docusaurus locally and everything checks out.
=> fix: correct linking for 'getting started' page

docs/cli/add.md
=> update add doc

docs/only-allow-pnpm.md
=> Use double quotes and escape to work on cmd.exe

docs/package_json.md
Update documentation for changes in pnpm/pnpm#2116
=> doc(publishConfig): add additional well-known fields

docs/cli/publish.md, docs/cli/remove.md, website/versioned_docs/version-3.8/cli/publish.md, website/versioned_docs/version-3.8/cli/remove.md, website/versioned_docs/version-4.12/cli/remove.md, website/versioned_docs/version-4.6/cli/publish.md, website/versioned_docs/version-4.7/cli/remove.md
Changed in the versioned docs as well.
=> Fix broken links to workspaces 

website/pages/en/Footer.js
From gitter chat, it seems discord is the primary communication platform.
=> Add discord link for project chat

website/versioned_docs/version-5.9/npmrc.md
Values from https://github.com/pnpm/pnpm/blob/master/packages/config/src/index.ts#L159-L160
=> Correct the default public-hoist-patterns

docs/using-changesets.md
add more changeset actions with pnpm
=> docs: add more changeset actions with pnpm

docs/continuous-integration.md
Added GitHub Actions Example to `docs/continuous-integration.md`
And more, speeding-up tips added
=> docs/continuous-integration: Add GitHub Actions

docs/continuous-integration.md
More specific instructions regarding `actions/setup-node@v2`
=> chore: update github action instructions

docs/pnpx-cli.md
Hey 👋 , I noticed this small typo while reading the docs and wanted to contribute to improving the docs.
(I couldn't find any contribution guidelines to follow, my apologies if I missed any steps)
=> docs: Fix pnpx docs typo and improve formatting

docs/using-changesets.md
I've been testing the publish workflow [here](https://github.com/verdaccio/monorepo) for a while, I think this workflow works just fine.
=> Add changeset publish flow update

versioned_docs/version-6.x/continuous-integration.md
=> docs(continuous-integration): add Bitbucket Pipelines

docs/cli/install.md
Just to make sure they don't get translated
=> Add inline code blocks

docs/workspaces.md, versioned_docs/version-6.x/workspaces.md
Helps users troubleshoot cyclic dependencies
=> Troubleshoot cyclic dependencies (#3569)

docs/cli/link.md, versioned_docs/version-6.x/cli/link.md
`pnpm link` cli docs are incomplite, so i have add some clarifications for variants of command
=> feat: add clarification for pnpm link command

docs/cli/recursive.md, versioned_docs/version-6.x/cli/recursive.md
Feature added in PR https://github.com/pnpm/pnpm/pull/3574
=> Add core-based workspace-concurrency

versioned_docs/version-6.x/faq.md
Really not a huge deal, but since there's a convenient edit button on the site, I figured I could help out with a quick fix. In the context that it's being used, "affect" is the appropriate verb.
See [Affect vs. Effect](https://www.merriam-webster.com/words-at-play/affect-vs-effect-usage-difference) for more details.
=> Minor spelling fix

users.json
Tiny PR to include Prisma in the https://pnpm.io/users page :)
=> add Prisma to list of users

docs/workspaces.md
Since 2/18/2021, commit: https://github.com/bytedance/bytemd/commit/36ef25f1ea1cd0b08752df5f8c832302017bb7fb
=> Add ByteMD as workspace example

docs/workspaces.md
=> docs: add VueUse and Slidev to workspace examples

docs/workspaces.md
Someone told me to add this here, not sure if you are actually looking for more examples, but Loving pnpm so far!
=> Add GiraphQL to examples

docs/package_json.md
Add example on how to override a package with an entirely different package (instead of just a different version)
=> Add "override" example in package_json.md

.github/workflows/ci.yml, docusaurus.config.js
- Only runs `en` build to ensure the website builds with a proposed changes
=> test website on pull request

src/pages/index.js
=> Center description test fix #155

.github/workflows/ci.yml
Fix error on failing pull request that don't have access to secrets
=> chore: remove download translations on ci

docs/installation.md
=> Fix PowerShell issue

src/pages/community.md
Hey! I'm a pnpm lover, a great tool to improve DX! Thanks!
I wrote an article mainly about how pnpm node_modules fold is structured which I think is an amazing improvement in Chinese in my personal blog and Japanese in my company tech blog.
Hope to help more and more people get familiar with pnpm!
=> Add Chinese and Japanese articles in community.md

docs/workspaces.md
[icestark](https://github.com/ice-lab/icestark) is a tool that assists individuals in developing micro fronentends. And it has changed to pnpm workspace at the first glance of pnpm.
=> Add icestark to pnpm workspace examples

docusaurus.config.js
=> fix the edit link

docs/pnpm-cli.md
=> Add link to workspaces page from CLI page

docs/workspaces.md
I like pnpm its sooo smart, and can i append my project into `examples`?
=> Add Tailchat to workspace examples

docs/using-changesets.md, docs/workspaces.md, src/pages/community.md, versioned_docs/version-5.x/workspaces.md
changed from https://github.com/atlassian/changesets to https://github.com/changesets/changesets
=> update changesets repo link

docs/continuous-integration.md
the've shut down more than 2 years ago https://twitter.com/sail_ci/status/1172960286636171264
=> remove SailCI

docs/installation.md
=> docs(installation): added scoop

docs/cli/add.md
Add the shorhand version of "--global" with an example.
=> add "-g" to docs

docs/workspaces.md
https://github.com/vitest-dev/vitest/commit/d6ff0ccb819716713f5eab5c046861f4d8e4f988
=> docs: add Vitest as an example of pnpm using the workspace feat

docs/cli/fetch.md
`backage.json` did make me chuckle though 😄
=> fix: fetch example typo

docs/npmrc.md
https://github.com/pnpm/pnpm/pull/4548
=> feat(npmrc): add docs about git-shallow-hosts

docs/package_json.md
Add typesVersions field to publishConfig
Please check if this pr is approved 🙇 
related pr: https://github.com/pnpm/pnpm/pull/4637
=> docs: add typesVersions field to publishConfig

docs/workspaces.md
Add NextAuth.js to workspace usage examples
=> docs: add NextAuth.js to usage examples

docs/using-changesets.md
```diff
- pnpm add -DW @changesets/cli
+ pnpm add -Dw @changesets/cli
```
=> fix(typo): pnpm add command capitalization error

docs/cli/update.md
Refs:
https://github.com/pnpm/pnpm/blob/13210db3c3c4f2f4ec3de0b6a1500d8389df3c93/packages/plugin-commands-installation/src/update/index.ts#L96
=> docs: add missing alias

src/pages/index.js, src/pages/styles.module.css
This pr should fix #290 
added media queries for the iframe and (potential) buttons overflow
=> fix: iframe and buttons overflow on mobile

docs/cli/deploy.md
=> fix: deploy example dockerfile

docs/continuous-integration.md
Add Azure Pipelines documentation to help users find example of implementation on Azure pipelines
=> Add Azure Pipelines documentation

docs/workspaces.md
Great work, thanks!
It'll be great if our project can be added in the list.
=> docs: add Logto usage example

docs/workspaces.md
We're big `pnpm` fans ❤️ 
([migration commit](https://github.com/vercel/turborepo/commit/fd171519ec02a69c9afafc1bc5d9d1b481fba721))
=> feat(docs): add turbo to workspace users

docs/workspaces.md, versioned_docs/version-6.x/workspaces.md, versioned_docs_archived/version-2.x/workspaces.md, versioned_docs_archived/version-5.x/workspaces.md
As the title above says, I add some contents for workspace to fix misleading.
=>  docs(workspace): add more details for workspace as a complementary

.github/workflows/translations.yml, docusaurus.config.js, package.json, pnpm-lock.yaml, scripts/progress_lang.json, scripts/translations.ts
The idea is avoid you have to do https://github.com/pnpm/pnpm.github.io/commit/67be17aedc48e6157a907c153cedcbb35f32cec9 manually.
~What's missing?, I can add another cron job that commit the progress file regularly, so the docusaurus just pick the latest from there.~ Done.
~Sorry the noise, seems we don't have common prettier settings.~
https://crowdin.github.io/crowdin-api-client-js/modules.html
=> chore: automated progress translations

docs/workspaces.md
I think this is a typo? It completely reverses the meaning and is quite confusing,
=> Update workspaces.md to fix mistake in workspaces docs

docs/cli/install.md, docs/continuous-integration.md, versioned_docs/version-6.x/continuous-integration.md
Use the official typesetting of GitLab.
Ref: https://about.gitlab.com/company/
=> docs: fix typesetting of "GitLab"

LICENSE
=> chore: create license

docs/cli/update.md
=> I think it's a typo

README.md
This PR adds a "Open in Codeflow IDE" button to the readme.
=> chore: add button to open the repo in codeflow ide

docs/cli/doctor.md, package.json, sidebars.json, versioned_sidebars/version-7.x-sidebars.json
Related PR: https://github.com/pnpm/pnpm/pull/5526
Node.js version from the [documentation](https://docusaurus.io/docs/installation#requirements) of docusaurus
=> feat: add pnpm doctor docs and engines.node

docs/installation.md
ref https://github.com/pnpm/pnpm/issues/5483
=> docs: add prerequisites section to installation page

docs/cli/audit.md, docs/package_json.md
Documents the audit--fix allowList feature: https://github.com/pnpm/pnpm/pull/5592
=> Document pnpm.auditConfig.ignoreCves

docs/cli/list.md, docs/cli/outdated.md, docs/cli/remove.md, docs/cli/update.md, docs/cli/why.md, versioned_docs/version-6.x/cli/list.md, versioned_docs/version-6.x/cli/outdated.md, versioned_docs/version-6.x/cli/remove.md, versioned_docs/version-6.x/cli/update.md, versioned_docs/version-6.x/cli/why.md
Fix the missing alias in the documentation.
=> docs: fix missing alias

src/pages/index.js
Tiny fix to use the correct alt tags for Nhost & Novu :)
=> fix: update sponsor alt tags

docs/continuous-integration.md
Related to https://github.com/pnpm/action-setup/issues/63.
=> Use major version for `pnpm/action-setup`

docs/cli/dlx.md, docs/cli/publish.md
* add `--json`, `--recursive, -r` option for publish command
* add `--shell-mode` option for dlx command
=> update publish command and dlx command

docs/continuous-integration.md
Should be 'corepack enable' instead of 'corepack enabled'
=> Fixed Jenkins corepack typo

docusaurus.config.js
Use color scheme (light vs. dark) depending on user preferences.
=> Default to system color scheme

community/tools.md
Request to add the missing description of syncpack to https://pnpm.io/community/tools, thanks a lot.
=> Add syncpack tool description

docs/continuous-integration.md
This will only work with node.js 16, so I am not sure if it is too soon or we can update it already.
=> Suggest to use corepack to install pnpm in CI

docs/installation.md
This resolves https://github.com/pnpm/pnpm/issues/6128
=> Change ~ to $HOME in alpine installation instructions

community/tools.md
- alphabetize the list of community tools
- add a link for Lockfile Explorer
=> Add Lockfile Explorer

docs/installation.md
- mention @pnpm/exe
- fix the prerequisite version of Node.js
=> mention @pnpm/exe on the installation doc

docs/workspaces.md
Thanks for the amazing project! At n8n (29k stars) we recently [switched to pnpm workspaces](https://github.com/n8n-io/n8n/pull/4429) and would love to be included in your showcase.
=> docs: Add n8n to workspaces examples

docs/continuous-integration.md
https://nodejs.org/api/corepack.html
'Added in: v16.9.0, v14.19.0'
=> node version Gitlab&Bitbucket image

docs/cli/fetch.md
=> docs: add short alias for `pnpm fetch`

docs/cli/fetch.md
Previous example led some people to issues described in https://github.com/pnpm/pnpm/issues/4897#issuecomment-1519034464
=> docs(fetch): add WORKDIR instruction in example Dockerfile

docs/package_json.md
This PR surfaces information from https://github.com/pnpm/pnpm/issues/6002#issuecomment-1465055241 to the related documentation page for more visibility.
Feel free to rephrase the content as needed.
=> Add info about updating injected dependencies

docs/installation.md
Hello,
I have added winget instalation command to installation.md
Best regards,
Maciej Błędkowski
=> Add winget to installation.md

docs/cli/update.md
related https://github.com/pnpm/pnpm/issues/6645
=> fix: update ignore patterns error

docs/cli/config.md, versioned_docs/version-7.x/cli/config.md
Fix wrong size title and some missing parameters
=> fix: wrong size title and typo

docs/pnpm-cli.md
fixes https://github.com/pnpm/pnpm/issues/6776
=> docs: environment variables

docs/errors.md
related change: https://github.com/pnpm/pnpm/pull/6916
=> docs: add new error codes

docs/installation.md
Volta has officially support pnpm: https://docs.volta.sh/advanced/pnpm
=> Add Volta to Installation

docs/pnpm-vs-npm.md
Heya,
I was reading this document and noticed a typo. This is me creating a pr to fix it
=> docs(pnpm-vs-npm): fix typo

docs/continuous-integration.md
Updated NodeJS image version in GitLab CI and BitBucket
=> Update NodeJS Image in CI

docs/cli/link.md
Close: https://github.com/pnpm/pnpm/issues/4640
=> docs (link): explain difference of arguments

community/articles.md
I've written an article analyzing the storage mechanism of pnpm, and I hope to add it to the article list.
=> feat(community): add chinese article

docs/cli/install.md
for https://github.com/pnpm/pnpm/issues/6300
=> Docs: add filter notice

docs/workspaces.md
=> workspaces: add Qwik to the list

docs/completion.md
* The medium article no longer applies to pnpm v9.
* Fig is being shutdown.
=> docs(completion): remove outdated information

docs/package_json.md
The conversation from https://github.com/pnpm/pnpm/issues/4407 has converged on two better solutions for resyncing injected dependencies:  `pnpm-sync` and `pnpm-sync-dependencies-meta-injected`.
=> docs: improve explanation for injected dependencies

docs/workspaces.md
What?
* Add Novu to the list (migration [commit](https://github.com/novuhq/novu/commit/f2ea61f7d7ac7e12db4c9e70767082841ed98b2b))
* Sort by current stars
Screenshot (https://pnpmio-spfd--3000--1d4c3cdd.local-credentialless.webcontainer.io/workspaces)
=> workspaces: add Novu to the list

docs/continuous-integration.md
This pull request updates the pnpm action-setup to version 4.
=> Update pnpm action-setup to v4

docs/workspaces.md
Closes https://github.com/pnpm/pnpm/issues/8172
=> docs(workspace): correct outdated information

docs/cli/exec.md
Related: https://github.com/pnpm/pnpm/pull/8176
=> docs(exec): reporter-hide-prefix

users.json
Hi, @zkochan
At MacPaw, we use pnpm in our projects. I've created this pull request to update users.json accordingly.
Thank you for considering this update.
Best regards,
Serhii Shramko
=> feat: add macpaw company to users.json

docs/workspaces.md
Hi All,
Thank you for the great work on PNPM.
Created this PR to add [Quasar Framework](https://quasar.dev) to the list of popular projects using PNPM.
Thank you!
=> Update workspaces.md to include Quasar Framework

docs/cli/outdated.md
rel https://github.com/pnpm/pnpm/pull/8523
=> feat: `outdated` command support `sort-by` option

docs/package_json.md
sync https://github.com/pnpm/pnpm/pull/8958
=> feat: add ignoredBuiltDependencies

docs/cli/add.md
Corrects a couple of typos in `add.md`.
=> doc(add): corrects typos

docs/docker.md, docs/npmrc.md
Closes https://github.com/pnpm/pnpm/issues/8975
=> docs(npmrc): sync-injected-deps-after-scripts

docs/cli/config.md
close https://github.com/pnpm/pnpm/issues/9396
refs https://github.com/pnpm/pnpm/pull/9316
=> docs: update config `--location` desc

docs/cli/self-update.md
- Update the docs with the latest versions
So people who copy & paste these command get at least the latest version (since people might not verify what the latest stable is)
=> docs: update self-update with latest stable versions

docs/pnpm-cli.md
link to the `--frozen-lockfile` heading.
=> docs: update wrong link

docs/catalogs.md
Fixes https://github.com/pnpm/pnpm/issues/9697
Related to https://github.com/pnpm/pnpm/pull/9517
=> docs: remove catalogs caveat regarding pnpm update

docs/catalogs.md, docs/settings.md, docs/settings/_cleanupUnusedCatalogs.mdx
rel https://github.com/pnpm/pnpm/pull/9793
=> feat: add `cleanupUnusedCatalogs` desc
